app/models/producto.py
from app import db

class Producto(db.Model):
    __tablename__ = 'producto'
    idproducto = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombrepdo = db.Column(db.String(255), nullable=False)
    descripcionpdo = db.Column(db.String(255), nullable=False)
    preciopdo = db.Column(db.BigInteger, nullable=False)
    stockpdo = db.Column(db.Integer, nullable=False)
    imagenpdo = db.Column(db.String(255))
    
    detalle_facturas = db.relationship("Detallefactura", back_populates="producto")

    idcategoria = db.Column(db.Integer, db.ForeignKey('categoria.idcategoria'))
    categoria = db.relationship('Categoria', back_populates='productos')

    idproveedor = db.Column(db.Integer, db.ForeignKey('proveedor.idproveedor'))
    proveedor = db.relationship('Proveedor', back_populates='productos')

app/routes/baseRoutes.py
from flask import Blueprint, render_template
from flask_login import login_required
from app.models.producto import Producto
from app.models.categoria import Categoria
from app.routes.carritoRoutes import carrito_compras



bp = Blueprint('menu', __name__)

@bp.route('/vista')
def vista():
    return render_template('menu/base.html')

@bp.route('/cafeteria')
@login_required
def cafeteria():
    productos = Producto.query.join(Categoria).filter(Categoria.tipocga == 'Cafetería').all()
    return render_template('menu/cafeteria.html', productos=productos, t=carrito_compras.tamañoD())

@bp.route('/restaurante')
@login_required
def restaurante():
    productos = Producto.query.join(Categoria).filter(Categoria.tipocga == 'Restaurante').all()
    return render_template('menu/restaurante.html', productos=productos, t=carrito_compras.tamañoD())

@bp.route('/panaderia')
@login_required
def panaderia():
    productos = Producto.query.join(Categoria).filter(Categoria.tipocga == 'Panadería').all()
    return render_template('menu/panaderia.html', productos=productos, t=carrito_compras.tamañoD())

app/routes/carritoRoutes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required
from app.models.producto import Producto
from app.models.carrito import Carrito
from app.models.factura import Factura
from app.models.detallefactura import Detallefactura
from app import db

bp = Blueprint('carrito', __name__)
carrito_compras = Carrito()

@bp.route('/ListarCarrito')
@login_required
def listar():
    items = carrito_compras.getItems()
    return render_template('productos/list.html', items=items)

@bp.route('/ListarProductos')
@login_required
def index():
    producto = carrito_compras
    return render_template('index.html', producto=producto)

@bp.route('/agregar/<int:id>/<path:referer>', methods=['POST'])
@login_required
def agregar_al_carrito(id, referer):
    cantidad = int(request.form['cantidad'])
    carrito_compras.agregar_producto(id, cantidad)
    return redirect(referer)

@bp.route('/eliminar/<int:id>', methods=['POST'])
@login_required
def eliminar_del_carrito(id):
    carrito_compras.eliminar_producto(id)
    return redirect(url_for('carrito.listar'))

@bp.route('/realizar_compra')
@login_required
def realizar_compra():
    total = carrito_compras.calcular_total()
    return render_template('carritos/realizar_compra.html', total=total)


@bp.route('/generar_factura', methods=['POST'])
@login_required
def generar_factura():
    total = carrito_compras.calcular_total()
    
    # Obtener el ID del cliente (aquí debes obtener el ID del cliente de alguna manera)
    id_cliente = 1  # Aquí debes obtener el ID del cliente, por ejemplo, de la sesión del usuario
    
    # Crear una nueva factura
    factura = Factura(fechafta='Hoy', idcliente=id_cliente)
    db.session.add(factura)
    db.session.commit()  # Guardar la factura para obtener el ID
    
    # Agregar detalles de la factura
    for item in carrito_compras.getItems():
        detallefactura = Detallefactura(
            idfactura=factura.idfactura,
            idproducto=item['producto'].idproducto,
            cantidad=item['cantidad']
        )
        db.session.add(detallefactura)
    
    db.session.commit()  # Guardar todos los detalles de la factura
    
    # Vaciar el carrito de compras
    carrito_compras.carrito = []
    
    return render_template('carritos/factura.html', total=total)

@bp.route('/itemscarrito', methods=['GET', 'POST'])
@login_required
def tCarrito():
    a = carrito_compras.tamañoD()
    print("Entra a carrito rutas", a)
    return f"Entra a carrito {carrito_compras.tamañoD()}"

app/routes/productoRoutes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required
from werkzeug.utils import secure_filename
from app.models.proveedor import Proveedor
from app.models.producto import Producto
from app.models.categoria import Categoria
from app.routes.carritoRoutes import carrito_compras
from app import db
import os

bp = Blueprint('producto', __name__)

@bp.route('/producto')
@login_required
def index():
    data = Producto.query.all()
    dataC = Categoria.query.all()
    dataP = Proveedor.query.all()
    return render_template('productos/index.html', data=data, dataC=dataC, dataP=dataP, t=carrito_compras.tamañoD())

@bp.route('/vista')
@login_required
def vista():
    data = Producto.query.all()
    dataC = Categoria.query.all()
    dataP = Proveedor.query.all()
    return render_template('menu/base.html', data=data, dataC=dataC, dataP=dataP, t=carrito_compras.tamañoD())

@bp.route('/Producto/add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'POST':
        nombrepdo = request.form['nombrepdo']
        idproveedor = request.form['nombrepvr']
        idcategoria = request.form['tipocga']
        descripcionpdo = request.form['descripcionpdo']
        preciopdo = request.form['preciopdo']
        stockpdo = request.form['stockpdo']

        imagenpdo = request.files['imagenpdo']

        if imagenpdo:
            filename = secure_filename(imagenpdo.filename)
            imagen_path = os.path.join('static', 'img', filename)
            imagenpdo.save(os.path.join(os.path.dirname(__file__), '..', imagen_path))
            ruta_imagen = imagen_path
        else:
            ruta_imagen = None

        newProducto = Producto(nombrepdo=nombrepdo, idcategoria=idcategoria, idproveedor=idproveedor, descripcionpdo=descripcionpdo, preciopdo=preciopdo, stockpdo=stockpdo, imagenpdo=imagenpdo.filename)
        db.session.add(newProducto)
        db.session.commit()

        categoria = Categoria.query.get(idcategoria)
        if categoria:
            if categoria.tipocga == 'Cafetería':
                return redirect(url_for('menu.cafeteria'))
            elif categoria.tipocga == 'Restaurante':
                return redirect(url_for('menu.restaurante'))
            elif categoria.tipocga == 'Panadería':
                return redirect(url_for('menu.panaderia'))

        return redirect(url_for('producto.index'))
    categorias = Categoria.query.all()
    proveedores = Proveedor.query.all()
    return render_template('productos/add.html', categorias=categorias, proveedores=proveedores)

@bp.route('/Producto/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    producto = Producto.query.get_or_404(id)
    categorias = Categoria.query.all()
    proveedores = Proveedor.query.all()

    if request.method == 'POST':
        producto.nombrepdo = request.form['nombrepdo']
        producto.idcategoria = request.form['tipocga']
        producto.idproveedor = request.form['nombrepvr']
        producto.descripcionpdo = request.form['descripcionpdo']
        producto.preciopdo = request.form['preciopdo']
        producto.stockpdo = request.form['stockpdo']
        db.session.commit()
        return redirect(url_for('producto.index'))

    return render_template('productos/edit.html', producto=producto, categorias=categorias, proveedores=proveedores)
    

@bp.route('/Producto/delete/<int:id>')
@login_required
def delete(id):
    producto = Producto.query.get_or_404(id)
    
    db.session.delete(producto)
    db.session.commit()

    return redirect(url_for('producto.index'))
@bp.route('/Producto/Listar/<int:id>', methods=['GET', 'POST'])
@login_required
def list(id):
    producto = Producto.query.get_or_404(id)

    if request.method == 'POST':
        producto.nombrepdo = request.form['nombrepdo']
        producto.idcategoria = request.form['tipocga']
        producto.idproveedor = request.form['nombrepvr']
        producto.descripcionpdo = request.form['descripcionpdo']
        producto.preciopdo = request.form['preciopdo']
        producto.stockpdo = request.form['stockpdo']
        db.session.commit()
        return redirect(url_for('producto.index'))

    # Renderizar la plantilla con los detalles del producto
    return render_template('productos/list.html', producto=producto)

    

app/templates/productos/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesss.css') }}" />
    <title>Agregar Prodcuto</title>
</head>
<body>
    <h1>Agregar Producto</h1>
    <form action="{{ url_for('producto.add') }}" method="post" enctype="multipart/form-data">
        <label for="nombrepdo">Nombre producto:</label>
        <input type="text" id="nombrepdo" name="nombrepdo" required>
        <label for="descripcionpdo">Descripcion:</label>
        <input type="text" id="descripcionpdo" name="descripcionpdo" required>
        <label for="preciopdo">Precio:</label>
        <input type="text" id="preciopdo" name="preciopdo" required>
        <label for="stockpdo">Stock:</label>
        <input type="text" id="stockpdo" name="stockpdo" required>

        <label for="tipocga">Categoría:</label>
        <select id="tipocga" name="tipocga" required>
            {% for categoria in categorias %}
                <option value="{{ categoria.idcategoria }}">{{ categoria.tipocga }}</option>
            {% endfor %}
        </select>
        
        <label for="nombrepvr">Proveedor:</label>
        <select id="nombrepvr" name="nombrepvr" required>
            {% for proveedor in proveedores %}
                <option value="{{ proveedor.idproveedor }}">{{ proveedor.nombrepvr }}</option>
            {% endfor %}
        </select>

        <label for="imagenpdo">Imagen:</label>
        <input type="file" id="imagenpdo" name="imagenpdo">

        <button type="submit">Agregar producto</button>
    </form>
</body>
</html>

app/templates/productos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesss.css') }}" />
    <title>Editar Producto</title>
</head>
<body>
    <h1>Editar producto</h1>
    <form action="{{ url_for('producto.edit', id=producto.idproducto) }}" method="post">

        <label for="nombrepdo">Nombre producto:</label>
        <input type="text" id="nombrepdo" name="nombrepdo" value="{{ producto.nombrepdo }}" required>
        <label for="descripcionpdo">Descripcion:</label>
        <input type="text" id="descripcionpdo" name="descripcionpdo" value="{{ producto.descripcionpdo }}" required>
        <label for="preciopdo">Precio:</label>
        <input type="text" id="preciopdo" name="preciopdo" value="{{ producto.preciopdo }}" required>
        <label for="stockpdo">Stock:</label>
        <input type="text" id="stockpdo" name="stockpdo" value="{{ producto.stockpdo }}" required>
        <label for="tipocga">Categoría:</label>
        <select id="tipocga" name="tipocga" required>
            {% for categoria in categorias %}
                <option value="{{ categoria.idcategoria }}" {% if producto.idcategoria == categoria.idcategoria %}selected{% endif %}>
                    {{ categoria.tipocga }}
                </option>
            {% endfor %}
        </select>
        <label for="nombrepvr">Proveedor</label>
        <select id="nombrepvr" name="nombrepvr" required>
            {% for proveedor in data %}
                <option value="{{ proveedor.idproveedor }}"{% if producto.ideproveedor == proveedor.idproveedor %}selected{% endif %}>
                    {{ proveedor.nombrepvr }}
                </option>
            {% endfor %}
        </select>
        <button type="submit">Actualizar producto</button>
    </form>
</body>
</html>

app/templates/productos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styless.css') }}" />
    <title>Producto</title>
</head>
<body>

    <h1>Lista de Productos</h1>
    <h1>Items Carrito {{ t }} </h1> 
    <a href="{{ url_for('carrito.listar') }}">Ir a carrito</a>
    <table>
        <tr>
            <th>ID</th>
            <th>Producto</th>
            <th>Categoria</th>
            <th>Proveedor</th>
            <th>Precio</th>
            <th>Número de Unidades</th>
            <th>Acciones</th>
        </tr>
        {% for producto in data %}
            <tr>
                <td>{{ producto.idproducto }}</td>
                <td>{{ producto.nombrepdo }}</td>
                <td>{{ producto.categoria.tipocga }}</td>
                <td>{{ producto.proveedor.nombrepvr }}</td>
                <td>{{ producto.preciopdo }}</td>
                <td>
                    <form action="{{ url_for('carrito.agregar_al_carrito', id = producto.idproducto, referer=request.url) }}" method="post" style="display:inline;">
                        <input type="number" name="cantidad" value="1" min="1">
                        <button type="submit">Agregar al carrito</button>
                    </form>
                </td>
                <td>
                    <a href="{{ url_for('producto.edit', id=producto.idproducto) }}">Editar</a>
                    <a href="{{ url_for('producto.delete', id=producto.idproducto) }}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('producto.add') }}">Agregar producto</a>
    <a href="{{ url_for('categoria.index') }}">Ir a categoria</a>
    <a href="{{ url_for('factura.index') }}">Ir a facturas</a>
    <a href="{{ url_for('clientes.index') }}">Ir a clientes</a>
    <a href="{{ url_for('proveedor.index') }}">Ir a proveedores</a>
    <a href="{{url_for('menu.vista')}}">Ir al inicio</a>
</body>
</html>

app/templates/productos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styless.css') }}" />
    <title>Carrito</title>
</head>
<body>
    <h1>Carrito</h1>
    <table>
        <tr>
            <th>Producto</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Acciones</th>
        </tr>
        {% for item in items %}
        
            <tr>
                <td>{{ item['producto'].nombrepdo }}</td>
                <td>{{ item['producto'].preciopdo }}</td>
                <td>{{ item['cantidad'] }}</td>
                <td>
                    <a href="{{ url_for('producto.edit', id=item['producto'].idproducto) }}">Editar</a>
                    <a href="{{ url_for('producto.delete', id=item['producto'].idproducto) }}">Eliminar</a>                  
                </td>
            </tr>
        {% endfor %}        
    </table>
    <a href="{{ url_for('carrito.realizar_compra') }}">Realizar compra</a>
    <a href="{{ url_for('producto.index') }}">Ir a Productos</a>
</body>
</html>