app/routes/baseRoutes.py
from flask import Blueprint, render_template
from flask_login import login_required
from app.models.producto import Producto
from app.models.categoria import Categoria
from app.routes.carritoRoutes import carrito_compras



bp = Blueprint('menu', __name__)

@bp.route('/vista')
def vista():
    return render_template('menu/base.html')

@bp.route('/cafeteria')
@login_required
def cafeteria():
    productos = Producto.query.join(Categoria).filter(Categoria.tipocga == 'Cafetería').all()
    return render_template('menu/cafeteria.html', productos=productos, t=carrito_compras.tamañoD())

@bp.route('/restaurante')
@login_required
def restaurante():
    productos = Producto.query.join(Categoria).filter(Categoria.tipocga == 'Restaurante').all()
    return render_template('menu/restaurante.html', productos=productos, t=carrito_compras.tamañoD())

@bp.route('/panaderia')
@login_required
def panaderia():
    productos = Producto.query.join(Categoria).filter(Categoria.tipocga == 'Panadería').all()
    return render_template('menu/panaderia.html', productos=productos, t=carrito_compras.tamañoD())

app/routes/carritoRoutes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required
from app.models.producto import Producto
from app.models.carrito import Carrito
from app.models.factura import Factura
from app.models.detallefactura import Detallefactura
from app import db

bp = Blueprint('carrito', __name__)
carrito_compras = Carrito()

@bp.route('/ListarCarrito')
@login_required
def listar():
    items = carrito_compras.getItems()
    return render_template('productos/list.html', items=items)

@bp.route('/ListarProductos')
@login_required
def index():
    producto = carrito_compras
    return render_template('index.html', producto=producto)

@bp.route('/agregar/<int:id>/<path:referer>', methods=['POST'])
@login_required
def agregar_al_carrito(id, referer):
    cantidad = int(request.form['cantidad'])
    carrito_compras.agregar_producto(id, cantidad)
    return redirect(referer)

@bp.route('/eliminar/<int:id>', methods=['POST'])
@login_required
def eliminar_del_carrito(id):
    carrito_compras.eliminar_producto(id)
    return redirect(url_for('carrito.listar'))

@bp.route('/realizar_compra')
@login_required
def realizar_compra():
    total = carrito_compras.calcular_total()
    return render_template('carritos/realizar_compra.html', total=total)


@bp.route('/generar_factura', methods=['POST'])
@login_required
def generar_factura():
    total = carrito_compras.calcular_total()
    
    # Obtener el ID del cliente (aquí debes obtener el ID del cliente de alguna manera)
    id_cliente = 1  # Aquí debes obtener el ID del cliente, por ejemplo, de la sesión del usuario
    
    # Crear una nueva factura
    factura = Factura(fechafta='Hoy', idcliente=id_cliente)
    db.session.add(factura)
    db.session.commit()  # Guardar la factura para obtener el ID
    
    # Agregar detalles de la factura
    for item in carrito_compras.getItems():
        detallefactura = Detallefactura(
            idfactura=factura.idfactura,
            idproducto=item['producto'].idproducto,
            cantidad=item['cantidad']
        )
        db.session.add(detallefactura)
    
    db.session.commit()  # Guardar todos los detalles de la factura
    
    # Vaciar el carrito de compras
    carrito_compras.carrito = []
    
    return render_template('carritos/factura.html', total=total)

@bp.route('/itemscarrito', methods=['GET', 'POST'])
@login_required
def tCarrito():
    a = carrito_compras.tamañoD()
    print("Entra a carrito rutas", a)
    return f"Entra a carrito {carrito_compras.tamañoD()}"

app/templates/menu/cafeteria.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0"
		/>
		<title>BakerSams</title>
		<link rel="icon" href="{{ url_for('static', filename='img/ico.ico') }}" type="image/x-icon">
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />
	</head>
	<body>
		<header>
			<div class="container-hero">
				<div class="container hero">
					<div class="customer-support">
						<img src="{{ url_for('static', filename='img/headp.svg') }}" alt="Auricular Icono">
						<div class="content-customer-support">
							<span class="text">Soporte al cliente</span>
							<span class="number">321-409-8166</span>
						</div>
					</div>

					<div class="container-logo">
						<img class="logo" src="{{ url_for('static', filename='img/Borcelle.jpg') }}" alt="Borcelle">
						<h1><a href="/">BakerSams</a></h1>
					</div>

					<div class="container-user">
						<img src="{{ url_for('static', filename='img/user.svg') }}" alt="Usuario Icono">
						<div class="divider"></div>
						<a href="/ListarCarrito">
							<img src="{{ url_for('static', filename='img/car.svg') }}" alt="Carrito Icono">
							<span class="cart-count">{{t}}</span>
						</a>
					</div>
					
				</div>
			</div>

			<div class="container-navbar">
				<nav class="navbar container">
					<i class="fa-solid fa-bars"></i>
					<ul class="menu">
						<li><a href="{{ url_for('menu.vista') }}">Inicio</a></li>
						<li><a href="{{ url_for('menu.restaurante') }}">Restaurante</a></li>
						<li><a href="{{ url_for('menu.cafeteria') }}">Cafeteria</a></li>
						<li><a href="{{ url_for('menu.panaderia') }}">Panaderia</a></li>
					</ul>

					<form class="search-form">
						<input type="search" placeholder="Buscar..." />
						<button class="btn-search">
							<img src="{{ url_for('static', filename='img/lupa.svg') }}" alt="Lupa Icono">
						</button>
					</form>
				</nav>
			</div>
		</header>

		<main class="main-content">
			<h1>Cafeteria</h1>
			<section class="container top-products">
				<div class="container-products">
					<!-- Producto 1 -->
					{% for producto in productos %}
					<div class="card-product">
						<div class="container-img">
							{% if producto.imagenpdo %}
                    			{% set direccion = 'img/' + producto.imagenpdo %}
                    				<img src="{{ url_for('static', filename=direccion) }}" alt="{{ producto.nombrepdo }}">
                			{% endif %}
						</div>
						<div class="content-card-product">
							<div class="stars">
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-regular fa-star"></i>
							</div>
							<h3>{{ producto.nombrepdo }}</h3>
							<div class="can">
								<form action="{{ url_for('carrito.agregar_al_carrito', id=producto.idproducto, referer=request.url) }}" method="post" style="display:inline;">
									<label for="cantidad-{{ producto.idproducto }}" style="display:block;">Cantidad:</label>
									<input type="number" id="cantidad-{{ producto.idproducto }}" name="cantidad" value="1" min="1" style="width: 40px;">
									<button type="submit" class="add-cart">
										<img src="{{ url_for('static', filename='img/car.svg') }}" alt="Carrito icono" />
									</button>
								</form>								
								<p class="price">{{ producto.preciopdo }}</p>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</section>

		<footer class="footer">
			<div class="container container-footer">
				<div class="menu-footer">
					<div class="contact-info">
						<p class="title-footer">Información de Contacto</p>
						<ul>
							<li>
								Dirección: Barrio Reino Unido,
								Cll 9N #8E-11
							</li>
							<li>Teléfono: 321-409-8166</li>
							<li>EmaiL: samuelavila051@gmail.com</li>
						</ul>
						<div class="social-icons">
							<a href="https://www.facebook.com/samuel.estradaavila?locale=es_LA" target="_blank">
								<span class="facebook">
									<img src="{{ url_for('static', filename='img/face.svg') }}" alt="Face Icono">
								</span>
							</a>
							<a href="https://www.instagram.com/samuel_avila05/">
								<span class="instagram">
									<img src="{{ url_for('static', filename='img/insta.svg') }}" alt="Instagram Icono">
								</span>
							</a>							
						</div>
					</div>

					<div class="information">
						<p class="title-footer">Información</p>
						<ul>
							<li><a href="#">Información Delivery</a></li>
							<li><a href="#">Politicas de Privacidad</a></li>
							<li><a href="#">Términos y condiciones</a></li>
							<li><a href="#">Contactános</a></li>
						</ul>
					</div>

					<div class="my-account">
						<p class="title-footer">Mi cuenta</p>

						<ul>
							<li><a href="#">Mi cuenta</a></li>
							<li><a href="#">Historial de ordenes</a></li>
							<li><a href="#">Lista de deseos</a></li>
						</ul>
					</div>

					<div class="newsletter">
						<p class="title-footer">Acerca de nosotros</p>

						<div class="content">
							<p>
								En BakerSams, ofrecemos panes frescos, café de calidad y un menú delicioso.
							</p>
							<br>
							<p>
								Nos encanta crear un ambiente acogedor donde te sientas como en casa.
							</p>
							<br>
							<p>
								¡Te esperamos!
							</p>
						</div>
					</div>
				</div>

				<div class="copyright">
					<p>
						Desarrollado por Samuel Estrada &copy; 2024
					</p>
				</div>
			</div>
		</footer>
		</main>
	</body>
</html>

app/templates/menu/panaderia.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0"
		/>
		<title>BakerSams</title>
		<link rel="icon" href="{{ url_for('static', filename='img/ico.ico') }}" type="image/x-icon">
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />
	</head>
	<body>
		<header>
			<div class="container-hero">
				<div class="container hero">
					<div class="customer-support">
						<img src="{{ url_for('static', filename='img/headp.svg') }}" alt="Auricular Icono">
						<div class="content-customer-support">
							<span class="text">Soporte al cliente</span>
							<span class="number">321-409-8166</span>
						</div>
					</div>

					<div class="container-logo">
						<img class="logo" src="{{ url_for('static', filename='img/Borcelle.jpg') }}" alt="Borcelle">
						<h1><a href="/">BakerSams</a></h1>
					</div>

					<div class="container-user">
						<img src="{{ url_for('static', filename='img/user.svg') }}" alt="Usuario Icono">
						<div class="divider"></div>
						<a href="/ListarCarrito">
							<img src="{{ url_for('static', filename='img/car.svg') }}" alt="Carrito Icono">
							<span class="cart-count">{{t}}</span>
						</a>
					</div>
					
				</div>
			</div>

			<div class="container-navbar">
				<nav class="navbar container">
					<i class="fa-solid fa-bars"></i>
					<ul class="menu">
						<li><a href="{{ url_for('menu.vista') }}">Inicio</a></li>
						<li><a href="{{ url_for('menu.restaurante') }}">Restaurante</a></li>
						<li><a href="{{ url_for('menu.cafeteria') }}">Cafeteria</a></li>
						<li><a href="{{ url_for('menu.panaderia') }}">Panaderia</a></li>
					</ul>

					<form class="search-form">
						<input type="search" placeholder="Buscar..." />
						<button class="btn-search">
							<img src="{{ url_for('static', filename='img/lupa.svg') }}" alt="Lupa Icono">
						</button>
					</form>
				</nav>
			</div>
		</header>

		<main class="main-content">
			<h1>Panaderia</h1>
			<section class="container top-products">
				<div class="container-products">
					<!-- Producto 1 -->
					{% for producto in productos %}
					<div class="card-product">
						<div class="container-img">
							{% if producto.imagenpdo %}
                    			{% set direccion = 'img/' + producto.imagenpdo %}
                    				<img src="{{ url_for('static', filename=direccion) }}" alt="{{ producto.nombrepdo }}">
                			{% endif %}
						</div>
						<div class="content-card-product">
							<div class="stars">
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-regular fa-star"></i>
							</div>
							<h3>{{ producto.nombrepdo }}</h3>
							<div class="can">
								<form action="{{ url_for('carrito.agregar_al_carrito', id=producto.idproducto, referer=request.url) }}" method="post" style="display:inline;">
									<label for="cantidad-{{ producto.idproducto }}" style="display:block;">Cantidad:</label>
									<input type="number" id="cantidad-{{ producto.idproducto }}" name="cantidad" value="1" min="1" style="width: 40px;">
									<button type="submit" class="add-cart">
										<img src="{{ url_for('static', filename='img/car.svg') }}" alt="Carrito icono" />
									</button>
								</form>								
								<p class="price">{{ producto.preciopdo }}</p>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</section>

		<footer class="footer">
			<div class="container container-footer">
				<div class="menu-footer">
					<div class="contact-info">
						<p class="title-footer">Información de Contacto</p>
						<ul>
							<li>
								Dirección: Barrio Reino Unido,
								Cll 9N #8E-11
							</li>
							<li>Teléfono: 321-409-8166</li>
							<li>EmaiL: samuelavila051@gmail.com</li>
						</ul>
						<div class="social-icons">
							<a href="https://www.facebook.com/samuel.estradaavila?locale=es_LA" target="_blank">
								<span class="facebook">
									<img src="{{ url_for('static', filename='img/face.svg') }}" alt="Face Icono">
								</span>
							</a>
							<a href="https://www.instagram.com/samuel_avila05/">
								<span class="instagram">
									<img src="{{ url_for('static', filename='img/insta.svg') }}" alt="Instagram Icono">
								</span>
							</a>							
						</div>
					</div>

					<div class="information">
						<p class="title-footer">Información</p>
						<ul>
							<li><a href="#">Información Delivery</a></li>
							<li><a href="#">Politicas de Privacidad</a></li>
							<li><a href="#">Términos y condiciones</a></li>
							<li><a href="#">Contactános</a></li>
						</ul>
					</div>

					<div class="my-account">
						<p class="title-footer">Mi cuenta</p>

						<ul>
							<li><a href="#">Mi cuenta</a></li>
							<li><a href="#">Historial de ordenes</a></li>
							<li><a href="#">Lista de deseos</a></li>
						</ul>
					</div>

					<div class="newsletter">
						<p class="title-footer">Acerca de nosotros</p>

						<div class="content">
							<p>
								En BakerSams, ofrecemos panes frescos, café de calidad y un menú delicioso.
							</p>
							<br>
							<p>
								Nos encanta crear un ambiente acogedor donde te sientas como en casa.
							</p>
							<br>
							<p>
								¡Te esperamos!
							</p>
						</div>
					</div>
				</div>

				<div class="copyright">
					<p>
						Desarrollado por Samuel Estrada &copy; 2024
					</p>
				</div>
			</div>
		</footer>
		</main>
	</body>
</html>

app/templates/menu/restaurante.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0"
		/>
		<title>BakerSams</title>
		<link rel="icon" href="{{ url_for('static', filename='img/ico.ico') }}" type="image/x-icon">
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />
	</head>
	<body>
		<header>
			<div class="container-hero">
				<div class="container hero">
					<div class="customer-support">
						<img src="{{ url_for('static', filename='img/headp.svg') }}" alt="Auricular Icono">
						<div class="content-customer-support">
							<span class="text">Soporte al cliente</span>
							<span class="number">321-409-8166</span>
						</div>
					</div>

					<div class="container-logo">
						<img class="logo" src="{{ url_for('static', filename='img/Borcelle.jpg') }}" alt="Borcelle">
						<h1><a href="/">BakerSams</a></h1>
					</div>

					<div class="container-user">
						<img src="{{ url_for('static', filename='img/user.svg') }}" alt="Usuario Icono">
						<div class="divider"></div>
						<a href="/ListarCarrito">
							<img src="{{ url_for('static', filename='img/car.svg') }}" alt="Carrito Icono">
							<span class="cart-count">{{t}}</span>
						</a>
					</div>
					
				</div>
			</div>

			<div class="container-navbar">
				<nav class="navbar container">
					<i class="fa-solid fa-bars"></i>
					<ul class="menu">
						<li><a href="{{ url_for('menu.vista') }}">Inicio</a></li>
						<li><a href="{{ url_for('menu.restaurante') }}">Restaurante</a></li>
						<li><a href="{{ url_for('menu.cafeteria') }}">Cafeteria</a></li>
						<li><a href="{{ url_for('menu.panaderia') }}">Panaderia</a></li>
					</ul>

					<form class="search-form">
						<input type="search" placeholder="Buscar..." />
						<button class="btn-search">
							<img src="{{ url_for('static', filename='img/lupa.svg') }}" alt="Lupa Icono">
						</button>
					</form>
				</nav>
			</div>
		</header>

		<main class="main-content">
			<h1>Restaurante</h1>
			<section class="container top-products">
				<div class="container-products">
					<!-- Producto 1 -->
					{% for producto in productos %}
					<div class="card-product">
						<div class="container-img">
							{% if producto.imagenpdo %}
                    			{% set direccion = 'img/' + producto.imagenpdo %}
                    				<img src="{{ url_for('static', filename=direccion) }}" alt="{{ producto.nombrepdo }}">
                			{% endif %}
						</div>
						<div class="content-card-product">
							<div class="stars">
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-solid fa-star"></i>
								<i class="fa-regular fa-star"></i>
							</div>
							<h3>{{ producto.nombrepdo }}</h3>
							<div class="can">
								<form action="{{ url_for('carrito.agregar_al_carrito', id=producto.idproducto, referer=request.url) }}" method="post" style="display:inline;">
									<label for="cantidad-{{ producto.idproducto }}" style="display:block;">Cantidad:</label>
									<input type="number" id="cantidad-{{ producto.idproducto }}" name="cantidad" value="1" min="1" style="width: 40px;">
									<button type="submit" class="add-cart">
										<img src="{{ url_for('static', filename='img/car.svg') }}" alt="Carrito icono" />
									</button>
								</form>								
								<p class="price">{{ producto.preciopdo }}</p>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</section>

		<footer class="footer">
			<div class="container container-footer">
				<div class="menu-footer">
					<div class="contact-info">
						<p class="title-footer">Información de Contacto</p>
						<ul>
							<li>
								Dirección: Barrio Reino Unido,
								Cll 9N #8E-11
							</li>
							<li>Teléfono: 321-409-8166</li>
							<li>EmaiL: samuelavila051@gmail.com</li>
						</ul>
						<div class="social-icons">
							<a href="https://www.facebook.com/samuel.estradaavila?locale=es_LA" target="_blank">
								<span class="facebook">
									<img src="{{ url_for('static', filename='img/face.svg') }}" alt="Face Icono">
								</span>
							</a>
							<a href="https://www.instagram.com/samuel_avila05/">
								<span class="instagram">
									<img src="{{ url_for('static', filename='img/insta.svg') }}" alt="Instagram Icono">
								</span>
							</a>							
						</div>
					</div>

					<div class="information">
						<p class="title-footer">Información</p>
						<ul>
							<li><a href="#">Información Delivery</a></li>
							<li><a href="#">Politicas de Privacidad</a></li>
							<li><a href="#">Términos y condiciones</a></li>
							<li><a href="#">Contactános</a></li>
						</ul>
					</div>

					<div class="my-account">
						<p class="title-footer">Mi cuenta</p>

						<ul>
							<li><a href="#">Mi cuenta</a></li>
							<li><a href="#">Historial de ordenes</a></li>
							<li><a href="#">Lista de deseos</a></li>
						</ul>
					</div>

					<div class="newsletter">
						<p class="title-footer">Acerca de nosotros</p>

						<div class="content">
							<p>
								En BakerSams, ofrecemos panes frescos, café de calidad y un menú delicioso.
							</p>
							<br>
							<p>
								Nos encanta crear un ambiente acogedor donde te sientas como en casa.
							</p>
							<br>
							<p>
								¡Te esperamos!
							</p>
						</div>
					</div>
				</div>

				<div class="copyright">
					<p>
						Desarrollado por Samuel Estrada &copy; 2024
					</p>
				</div>
			</div>
		</footer>
		</main>
	</body>
</html>