app/models/factura.py
from datetime import datetime
from app import db

class Factura(db.Model):
    __tablename__ = 'factura'
    idfactura = db.Column(db.Integer, primary_key=True, autoincrement=True)
    fechafta = db.Column(db.DateTime, default=datetime.utcnow)
    idcliente = db.Column(db.Integer, db.ForeignKey('cliente.idcliente'))

    cliente = db.relationship("Cliente", back_populates="facturas")
    productos = db.relationship("Detallefactura", back_populates="factura")

    idmetodopago = db.Column(db.Integer, db.ForeignKey('metodopago.idmetodopago'))
    metodopago = db.relationship('Metodopago', back_populates='facturas')

app/routes/facturaRoutes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from flask_login import login_required
from app.models.factura import Factura
from app.models.detallefactura import Detallefactura
from app.routes.carritoRoutes import carrito_compras
from app import db

bp = Blueprint('factura', __name__)

@bp.route('/factura')
@login_required
def index():
    data = Factura.query.all()
    return render_template('facturas/index.html', data=data)
 

@bp.route('/addfactura', methods=['GET', 'POST'])
@login_required
def add():
    db.session.add(factura)
    db.session.commit()
    print("factura id  ", factura.idfactura)
    return redirect(url_for('factura.addDetalle',id=factura.idfactura))

@bp.route('/adddetalle/<int:id>', methods=['GET', 'POST'])
@login_required
def addDetalle(id):
    for item in carrito_compras.getItems():
        idproducto = item["producto"].idproducto
        cantidad = item["cantidad"]
        detallefactura = Detallefactura(idfactura=id, idproducto=idproducto, cantidad=cantidad)
        db.session.add(detallefactura)
    
    db.session.commit()  # Mover commit fuera del bucle para mejorar el rendimiento
    carrito_compras.vaciarcarrito()
    return redirect(url_for('producto.index'))


@bp.route('/factura/<int:id>', methods=['GET', 'POST'])
@login_required
def detalle(id):
    factura = Factura.query.get_or_404(id)
    detalle = factura.productos  # Cambiar `factura.producto` a `factura.productos`
    return render_template('detalles/index.html', data=detalle, factura=factura)


@bp.route('/delete/<int:id>')
@login_required
def delete(id):
    factura = Factura.query.get_or_404(id)
    
    db.session.delete(factura)
    db.session.commit()

    return redirect(url_for('factura.index'))

app/templates/facturas/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesss.css') }}" />
    <title>Agregar factura</title>
</head>
<body>
    <h1>Agregar factura</h1>
    <form action="{{ url_for('factura.add') }}" method="post">
        <label for="fechafta">Fecha:</label>
        <input type="text" id="fechafta" name="fechafta" required>
        <label for="idcliente">Cliente:</label>
        <select id="idcliente" name="idcliente">
            {% for cliente in data %}
                <option value="{{ idcliente.id }}">{{ idcliente.idcliente }}</option>
            {% endfor %}
        </select>
        <button type="submit">Agregar factura</button>
    </form>
</body>
</html>

app/templates/facturas/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styless.css') }}" />
    <title>Facturas</title>
</head>
<body>
    <h1>Facturas</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Fecha</th>
            <th>ID Cliente</th>
            <th>Acciones</th>
        </tr>
        {% for factura in data %}
            <tr>
                <td>{{ factura.idfactura }}</td>
                <td>{{ factura.fechafta }}</td>
                <td>{{ factura.idcliente }}</td>
                <td>
                    <a href="{{ url_for('factura.delete', id=factura.idfactura) }}">Eliminar</a> 
                    <a href="{{ url_for('factura.detalle', id=factura.idfactura) }}">Ver factura</a>                
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('producto.index') }}">Ir a Productos</a>
</body>
</html>